SELECT location_id INTO @locationId FROM location WHERE location.name='Kahramana(1st floor)';
update bed_location_map set row_number=2, column_number=2 where location_id=@locationId and row_number=1 and column_number=5;
update bed_location_map set row_number=2, column_number=1 where location_id=@locationId and row_number=1 and column_number=4;
update bed_location_map set column_number=7 where location_id=@locationId and row_number=1 and column_number=3;
update bed_location_map set column_number=5 where location_id=@locationId and row_number=1 and column_number=2;
update bed_location_map set column_number=4 where location_id=@locationId and row_number=1 and column_number=1;

CALL insertBedIntoLocation('110/1', 'Kahramana(1st floor)',1,1);
CALL insertBedIntoLocation('110/2', 'Kahramana(1st floor)',1,2);
CALL insertBedIntoLocation('110/3', 'Kahramana(1st floor)',1,3);
CALL insertBedIntoLocation('111/3', 'Kahramana(1st floor)',1,6);

SELECT location_id INTO @locationId FROM location WHERE location.name='Buffer Beds';
update bed_location_map set row_number=1, column_number=8 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='103/3');
update bed_location_map set row_number=1, column_number=9 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='104/1');
update bed_location_map set row_number=2, column_number=1 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='104/2');
update bed_location_map set row_number=2, column_number=2 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='105/1');
update bed_location_map set row_number=2, column_number=3 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='105/2');
update bed_location_map set row_number=2, column_number=5 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='106/1');
update bed_location_map set row_number=2, column_number=6 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='106/2');
update bed_location_map set row_number=2, column_number=7 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='107/1');
update bed_location_map set row_number=2, column_number=8 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='107/2');
update bed_location_map set row_number=2, column_number=9 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='107/3');
update bed_location_map set row_number=3, column_number=1 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='107/4');
update bed_location_map set row_number=3, column_number=2 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='108/1');
update bed_location_map set row_number=3, column_number=3 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='108/2');
update bed_location_map set row_number=3, column_number=4 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='108/3');
update bed_location_map set row_number=3, column_number=5 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='109/1');
update bed_location_map set row_number=3, column_number=6 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='109/2');
update bed_location_map set row_number=3, column_number=7 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='109/3');
update bed_location_map set row_number=3, column_number=8 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='109/4');
update bed_location_map set row_number=3, column_number=9 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='109/5');
update bed_location_map set row_number=4, column_number=1 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='112/1');
update bed_location_map set row_number=4, column_number=2 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='112/2');
update bed_location_map set row_number=4, column_number=3 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='112/3');
update bed_location_map set row_number=4, column_number=4 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='113/1');
update bed_location_map set row_number=4, column_number=5 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='113/2');
update bed_location_map set row_number=4, column_number=6 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='114/1');
update bed_location_map set row_number=4, column_number=7 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='114/2');
update bed_location_map set row_number=4, column_number=8 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='114/3');
update bed_location_map set row_number=4, column_number=9 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='117/1');
update bed_location_map set row_number=5, column_number=1 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='117/2');
update bed_location_map set row_number=5, column_number=2 where location_id=@locationId and bed_id in (select bed_id from bed where bed_number='117/3');

CALL insertBedIntoLocation('105/3','Buffer Beds',2,4);
CALL insertBedIntoLocation('301/1','Buffer Beds',5,3);
CALL insertBedIntoLocation('301/2','Buffer Beds',5,4);
CALL insertBedIntoLocation('302/1','Buffer Beds',5,5);
CALL insertBedIntoLocation('302/2','Buffer Beds',5,6);
CALL insertBedIntoLocation('303/1','Buffer Beds',5,7);
CALL insertBedIntoLocation('303/2','Buffer Beds',5,8);
CALL insertBedIntoLocation('303/3','Buffer Beds',5,9);
CALL insertBedIntoLocation('304/1','Buffer Beds',6,1);
CALL insertBedIntoLocation('304/2','Buffer Beds',6,2);
CALL insertBedIntoLocation('305/1','Buffer Beds',6,3);
CALL insertBedIntoLocation('305/2','Buffer Beds',6,4);
CALL insertBedIntoLocation('305/3','Buffer Beds',6,5);
CALL insertBedIntoLocation('306/1','Buffer Beds',6,6);
CALL insertBedIntoLocation('306/2','Buffer Beds',6,7);
CALL insertBedIntoLocation('307/1','Buffer Beds',6,8);
CALL insertBedIntoLocation('307/2','Buffer Beds',6,9);
CALL insertBedIntoLocation('307/3','Buffer Beds',7,1);
CALL insertBedIntoLocation('308/1','Buffer Beds',7,2);
CALL insertBedIntoLocation('308/2','Buffer Beds',7,3);
CALL insertBedIntoLocation('309/1','Buffer Beds',7,4);
CALL insertBedIntoLocation('309/2','Buffer Beds',7,5);
CALL insertBedIntoLocation('309/3','Buffer Beds',7,6);
CALL insertBedIntoLocation('310/1','Buffer Beds',7,7);
CALL insertBedIntoLocation('310/2','Buffer Beds',7,8);
CALL insertBedIntoLocation('310/3','Buffer Beds',7,9);
CALL insertBedIntoLocation('311/1','Buffer Beds',8,1);
CALL insertBedIntoLocation('311/2','Buffer Beds',8,2);
CALL insertBedIntoLocation('311/3','Buffer Beds',8,3);
CALL insertBedIntoLocation('311/4','Buffer Beds',8,4);
CALL insertBedIntoLocation('312/1','Buffer Beds',8,5);
CALL insertBedIntoLocation('312/2','Buffer Beds',8,6);
CALL insertBedIntoLocation('312/3','Buffer Beds',8,7);
CALL insertBedIntoLocation('313/1','Buffer Beds',8,8);
CALL insertBedIntoLocation('313/2','Buffer Beds',8,9);
CALL insertBedIntoLocation('314/1','Buffer Beds',9,1);
CALL insertBedIntoLocation('314/2','Buffer Beds',9,2);
CALL insertBedIntoLocation('315/1','Buffer Beds',9,3);
CALL insertBedIntoLocation('315/2','Buffer Beds',9,4);
CALL insertBedIntoLocation('316/1','Buffer Beds',9,5);
CALL insertBedIntoLocation('316/2','Buffer Beds',9,6);
CALL insertBedIntoLocation('317/1','Buffer Beds',9,7);
CALL insertBedIntoLocation('317/2','Buffer Beds',9,8);
CALL insertBedIntoLocation('317/3','Buffer Beds',9,9);
CALL insertBedIntoLocation('318/1','Buffer Beds',10,1);
CALL insertBedIntoLocation('318/2','Buffer Beds',10,2);
CALL insertBedIntoLocation('318/3','Buffer Beds',10,3);
