SELECT location_id INTO @KahramanaFirstFloorLocationId FROM location WHERE location.name='Kahramana(1st floor)';
SELECT location_id INTO @BufferBedsLocationId FROM location WHERE location.name='Buffer Beds';

update bed_location_map set row_number=5, column_number=1 where location_id=@KahramanaFirstFloorLocationId and row_number=1 and column_number=1;
update bed_location_map set row_number=5, column_number=2 where location_id=@KahramanaFirstFloorLocationId and row_number=1 and column_number=2;
update bed_location_map set row_number=5, column_number=3 where location_id=@KahramanaFirstFloorLocationId and row_number=1 and column_number=3;
update bed_location_map set row_number=5, column_number=4 where location_id=@KahramanaFirstFloorLocationId and row_number=1 and column_number=4;
update bed_location_map set row_number=5, column_number=5 where location_id=@KahramanaFirstFloorLocationId and row_number=1 and column_number=5;
update bed_location_map set row_number=5, column_number=6 where location_id=@KahramanaFirstFloorLocationId and row_number=1 and column_number=6;
update bed_location_map set row_number=7, column_number=1 where location_id=@KahramanaFirstFloorLocationId and row_number=1 and column_number=7;
update bed_location_map set row_number=7, column_number=2 where location_id=@KahramanaFirstFloorLocationId and row_number=2 and column_number=1;
update bed_location_map set row_number=7, column_number=3 where location_id=@KahramanaFirstFloorLocationId and row_number=2 and column_number=2;
update bed_location_map set row_number=1, column_number=1, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=1 and column_number=1;
update bed_location_map set row_number=1, column_number=2, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=1 and column_number=2;
update bed_location_map set row_number=1, column_number=3, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=1 and column_number=3;
update bed_location_map set row_number=1, column_number=4, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=1 and column_number=4;
update bed_location_map set row_number=1, column_number=5, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=1 and column_number=5;
CALL insertBedIntoLocation('102/3', 'Kahramana(1st floor)',1,6);
update bed_location_map set row_number=1, column_number=7, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=1 and column_number=6;
update bed_location_map set row_number=2, column_number=1, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=1 and column_number=7;
update bed_location_map set row_number=2, column_number=2, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=1 and column_number=8;
update bed_location_map set row_number=2, column_number=3, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=1 and column_number=9;
update bed_location_map set row_number=2, column_number=4, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=2 and column_number=1;
update bed_location_map set row_number=2, column_number=5, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=2 and column_number=2;
update bed_location_map set row_number=2, column_number=6, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=2 and column_number=3;
update bed_location_map set row_number=2, column_number=7, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=2 and column_number=4;
update bed_location_map set row_number=3, column_number=1, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=2 and column_number=5;
update bed_location_map set row_number=3, column_number=2, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=2 and column_number=6;
update bed_location_map set row_number=3, column_number=3, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=2 and column_number=7;
update bed_location_map set row_number=3, column_number=4, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=2 and column_number=8;
update bed_location_map set row_number=3, column_number=5, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=2 and column_number=9;
update bed_location_map set row_number=3, column_number=6, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=3 and column_number=1;
update bed_location_map set row_number=3, column_number=7, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=3 and column_number=2;
update bed_location_map set row_number=4, column_number=1, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=3 and column_number=3;
update bed_location_map set row_number=4, column_number=2, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=3 and column_number=4;
update bed_location_map set row_number=4, column_number=3, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=3 and column_number=5;
update bed_location_map set row_number=4, column_number=4, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=3 and column_number=6;
update bed_location_map set row_number=4, column_number=5, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=3 and column_number=7;
update bed_location_map set row_number=4, column_number=6, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=3 and column_number=8;
update bed_location_map set row_number=4, column_number=7, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=3 and column_number=9;
update bed_location_map set row_number=5, column_number=7, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=4 and column_number=1;
update bed_location_map set row_number=6, column_number=1, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=4 and column_number=2;
update bed_location_map set row_number=6, column_number=2, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=4 and column_number=3;
update bed_location_map set row_number=6, column_number=3, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=4 and column_number=4;
update bed_location_map set row_number=6, column_number=4, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=4 and column_number=5;
update bed_location_map set row_number=6, column_number=5, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=4 and column_number=6;
update bed_location_map set row_number=6, column_number=6, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=4 and column_number=7;
update bed_location_map set row_number=6, column_number=7, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=4 and column_number=8;
update bed_location_map set row_number=7, column_number=4, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=4 and column_number=9;
update bed_location_map set row_number=7, column_number=5, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=5 and column_number=1;
update bed_location_map set row_number=7, column_number=6, location_id=@KahramanaFirstFloorLocationId where location_id=@BufferBedsLocationId and row_number=5 and column_number=2;


update bed_location_map set row_number=1, column_number=1 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='301/1');
update bed_location_map set row_number=1, column_number=2 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='301/2');
update bed_location_map set row_number=1, column_number=3 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='302/1');
update bed_location_map set row_number=1, column_number=4 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='302/2');
update bed_location_map set row_number=1, column_number=5 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='303/1');
update bed_location_map set row_number=1, column_number=6 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='303/2');
update bed_location_map set row_number=1, column_number=7 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='303/3');
update bed_location_map set row_number=2, column_number=1 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='304/1');
update bed_location_map set row_number=2, column_number=2 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='304/2');
update bed_location_map set row_number=2, column_number=3 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='305/1');
update bed_location_map set row_number=2, column_number=4 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='305/2');
update bed_location_map set row_number=2, column_number=5 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='305/3');
update bed_location_map set row_number=2, column_number=6 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='306/1');
update bed_location_map set row_number=2, column_number=7 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='306/2');
update bed_location_map set row_number=3, column_number=1 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='307/1');
update bed_location_map set row_number=3, column_number=2 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='307/2');
update bed_location_map set row_number=3, column_number=3 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='307/3');
update bed_location_map set row_number=3, column_number=4 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='308/1');
update bed_location_map set row_number=3, column_number=5 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='308/2');
update bed_location_map set row_number=3, column_number=6 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='309/1');
update bed_location_map set row_number=3, column_number=7 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='309/2');
update bed_location_map set row_number=4, column_number=1 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='309/3');
update bed_location_map set row_number=4, column_number=2 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='310/1');
update bed_location_map set row_number=4, column_number=3 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='310/2');
update bed_location_map set row_number=4, column_number=4 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='310/3');
update bed_location_map set row_number=4, column_number=5 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='311/1');
update bed_location_map set row_number=4, column_number=6 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='311/2');
update bed_location_map set row_number=4, column_number=7 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='311/3');
update bed_location_map set row_number=5, column_number=1 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='311/4');
update bed_location_map set row_number=5, column_number=2 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='312/1');
update bed_location_map set row_number=5, column_number=3 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='312/2');
update bed_location_map set row_number=5, column_number=4 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='312/3');
update bed_location_map set row_number=5, column_number=5 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='313/1');
update bed_location_map set row_number=5, column_number=6 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='313/2');
update bed_location_map set row_number=5, column_number=7 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='314/1');
update bed_location_map set row_number=6, column_number=1 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='314/2');
CALL insertBedIntoLocation('314/3', 'Buffer Beds',6,2);
update bed_location_map set row_number=6, column_number=3 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='315/1');
update bed_location_map set row_number=6, column_number=4 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='315/2');
update bed_location_map set row_number=6, column_number=5 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='316/1');
update bed_location_map set row_number=6, column_number=6 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='316/2');
update bed_location_map set row_number=6, column_number=7 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='317/1');
update bed_location_map set row_number=7, column_number=1 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='317/2');
update bed_location_map set row_number=7, column_number=2 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='317/3');
update bed_location_map set row_number=7, column_number=3 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='318/1');
update bed_location_map set row_number=7, column_number=4 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='318/2');
update bed_location_map set row_number=7, column_number=5 where location_id=@BufferBedsLocationId and bed_id in (select bed_id from bed where bed_number='318/3');
CALL insertBedIntoLocation('318/4', 'Buffer Beds',7,6);

update location set name='Kahramana(3rd floor)', description='Hotel kahramana 3rd floor' where name='Buffer Beds';
