call create_reference_mapping_msf_internal('MH, Name of MLO', 'MLO');
call create_reference_mapping_msf_internal('MH, Network Area', 'NETWORK');
call create_reference_mapping_msf_internal('MH, Referred by', 'REFERRED');
call create_reference_mapping_msf_internal('MH, Date of injury', 'D_INJURY');
call create_reference_mapping_msf_internal('MH, Cause of injury', 'C_INJURY');
call create_reference_mapping_msf_internal('MH, Patient General Condition', 'PGENCON');
call create_reference_mapping_msf_internal('MH, If caretaker is needed, why?', 'NEEDCT');
call create_reference_mapping_msf_internal('Dr. Aziz Abu Azizeh', '1');
call create_reference_mapping_msf_internal('Dr. Medya Rasheed', '2');
call create_reference_mapping_msf_internal('Dr. Abdulhmeed Qaradaya', '3');
call create_reference_mapping_msf_internal('Dr. Feras Nasr', '4');
call create_reference_mapping_msf_internal('Dr. Wisam Hussam', '5');
call create_reference_mapping_msf_internal('Dr. Mohammed Hamed', '6');
call create_reference_mapping_msf_internal('Dr. Ali Arkan', '7');
call create_reference_mapping_msf_internal('Dr. Hozak Zaheer', '8');
call create_reference_mapping_msf_internal('Dr. Anas Ahmed', '9');
call create_reference_mapping_msf_internal('Dr. Israa Al Jumaily', '10');
call create_reference_mapping_msf_internal('Dr. Haider Abdulkareem Qasim', '11');
call create_reference_mapping_msf_internal('Dr. Nadhum Duriad Nadhum', '12');
call create_reference_mapping_msf_internal('Dr. Omar Adil Alani', '13');
call create_reference_mapping_msf_internal('Dr. Aso Sulaiman Qahraman', '14');
call create_reference_mapping_msf_internal('Dr. Ehsan Al Masri', '15');
call create_reference_mapping_msf_internal('Dr. Meayada Ali Obeid', '16');
call create_reference_mapping_msf_internal('Dr. Wafa Al-Shawa', '17');
call create_reference_mapping_msf_internal('Aden Network', '1');
call create_reference_mapping_msf_internal('Gaza Network', '2');
call create_reference_mapping_msf_internal('Al Anbar Network', '3');
call create_reference_mapping_msf_internal('Baghdad Network', '4');
call create_reference_mapping_msf_internal('Erbil Network', '5');
call create_reference_mapping_msf_internal('Kirkuk Network', '6');
call create_reference_mapping_msf_internal('Diyala Network', '7');
call create_reference_mapping_msf_internal('Dohuk Network', '8');
call create_reference_mapping_msf_internal('Karbala Network', '9');
call create_reference_mapping_msf_internal('Najaf Network', '10');
call create_reference_mapping_msf_internal('Nineveh Network', '11');
call create_reference_mapping_msf_internal('Salahadin Network', '12');
call create_reference_mapping_msf_internal('Sulaymaniyah Network', '13');
call create_reference_mapping_msf_internal('Kilis Network', '14');
call create_reference_mapping_msf_internal('Sanliurfa Network', '15');
call create_reference_mapping_msf_internal('Gaziantep Network', '16');
call create_reference_mapping_msf_internal('Hatay Network', '17');
call create_reference_mapping_msf_internal("Sana'a Network", '18');
call create_reference_mapping_msf_internal('Jordan Network', '19');
call create_reference_mapping_msf_internal('Blunt - Road traffic crash (War)', '1');
call create_reference_mapping_msf_internal('Blunt - Collapsed buildings and falls', '2');
call create_reference_mapping_msf_internal('Blunt - Explosions and anti-tank mines', '3');
call create_reference_mapping_msf_internal('Blunt - Beatings', '4');
call create_reference_mapping_msf_internal('Penetrating - Fragment wounds', '5');
call create_reference_mapping_msf_internal('Penetrating - Bullet wounds', '6');
call create_reference_mapping_msf_internal("Penetrating - Cut wounds 'arme blanche'", '7');
call create_reference_mapping_msf_internal('Anti-personal landmine wounds', '8');
call create_reference_mapping_msf_internal('Explosive blast injuries', '10');
call create_reference_mapping_msf_internal('Burns', '11');
call create_reference_mapping_msf_internal('Non-conventional weapons', '12');
call create_reference_mapping_msf_internal('Road traffic accident', '13');
call create_reference_mapping_msf_internal('Domestic accident', '14');
call create_reference_mapping_msf_internal('Other', '9');
call create_reference_mapping_msf_internal('Walking alone', '1');
call create_reference_mapping_msf_internal('Crutches', '2');
call create_reference_mapping_msf_internal('Walking frame', '3');
call create_reference_mapping_msf_internal('Walking cane', '4');
call create_reference_mapping_msf_internal('wheelchair', '5');
call create_reference_mapping_msf_internal('Bedridden', '6');
call create_reference_mapping_msf_internal('Under 18 years', '1');
call create_reference_mapping_msf_internal('Female above 18 Years w/o disability', '2');
call create_reference_mapping_msf_internal('Functional disability', '3');
call create_reference_mapping_msf_internal('Psycho-social disability', '4');
call create_reference_mapping_msf_internal('FSTG, Type of medical information received', 'TYPE_MEDINFO');
call create_reference_mapping_msf_internal('FSTG, Date received', 'D_RECEIVED');
call create_reference_mapping_msf_internal('FSTG, Is the medical file complete?', 'COMPLETE_FILE');
call create_reference_mapping_msf_internal('FSTG, Document(s) needed to be complete', 'NEEDED_DOCS');
call create_reference_mapping_msf_internal('FSTG, Specialty determined by MLO', 'SPECIALTY');
call create_reference_mapping_msf_internal('Stage', 'PTSTAGE');
call create_reference_mapping_msf_internal('FSTG, Date of presentation at 1st stage', 'D_PRESENTATION');
call create_reference_mapping_msf_internal('FSTG, Outcomes for 1st stage surgical validation', 'OUT_1STSURG');
call create_reference_mapping_msf_internal('FSTG, Priority', 'PRIORITY');
call create_reference_mapping_msf_internal('FSTG, Name (s) of Surgeon 1', 'SURGEON');
call create_reference_mapping_msf_internal('FSTG, Name (s) of Surgeon 2', 'SURGEON');
call create_reference_mapping_msf_internal('FSTG, Does the Patient need Surgical Final Validation', 'NEEDFV');
call create_reference_mapping_msf_internal('FSTG, Comments', 'COMMENTS');
call create_reference_mapping_msf_internal('FSTG, Outcomes for 1st stage Anaesthesia validation', 'OUT_1STANAESTH');
call create_reference_mapping_msf_internal('FSTG, Name (s) of Anaesthetist', 'ANAESTHETIST');
call create_reference_mapping_msf_internal('FSTG, Comments about Anaesthesia validation', 'COMMENTS');
call create_reference_mapping_msf_internal('FSTG, Postpone reason', 'PP_REASON');
call create_reference_mapping_msf_internal('FSTG, Comments about postpone reason', 'COMMENTS_PP');
call create_reference_mapping_msf_internal('FSTG, Medical file to be submitted again by', 'DATE_RESUB');
call create_reference_mapping_msf_internal('FSTG, Type of medical information needed for next submission', 'TYPE_MEDINFO_RESUB');
call create_reference_mapping_msf_internal('FST, Type of medical information needed for next submission', 'TYPE_MEDINFO_RESUB');
call create_reference_mapping_msf_internal('FSTG, Refused Reason', 'REFUSED_REASON');
call create_reference_mapping_msf_internal('FSTG, Comments about refusal', 'COMMENTS_REFUSAL');
call create_reference_mapping_msf_internal('New medical file', '1');
call create_reference_mapping_msf_internal('Updated Medical file', '2');
call create_reference_mapping_msf_internal('Anaesthesia update', '3');
call create_reference_mapping_msf_internal('Yes', '1');
call create_reference_mapping_msf_internal('No', '0');
call create_reference_mapping_msf_internal('Orthopedic', '1');
call create_reference_mapping_msf_internal('Plastic', '2');
call create_reference_mapping_msf_internal('Maxillofacial', '3');
call create_reference_mapping_msf_internal('Valid', '1');
call create_reference_mapping_msf_internal('Postponed', '2');
call create_reference_mapping_msf_internal('More Information', '3');
call create_reference_mapping_msf_internal('Refused', '4');
call create_reference_mapping_msf_internal('Low', '1');
call create_reference_mapping_msf_internal('Moderate', '2');
call create_reference_mapping_msf_internal('High', '3');
call create_reference_mapping_msf_internal('Urgent', '4');
call create_reference_mapping_msf_internal('Dr. Ali Al-Ani', '1');
call create_reference_mapping_msf_internal('Dr. Sofian Al-Qassab', '2');
call create_reference_mapping_msf_internal('Dr. Hanna Janho', '3');
call create_reference_mapping_msf_internal('Dr. Ashraf Nabhan', '4');
call create_reference_mapping_msf_internal('Dr. Rasheed Al Samerai', '5');
call create_reference_mapping_msf_internal('Dr. Muckhaled Naseef', '6');
call create_reference_mapping_msf_internal('Dr. Nasr Al-Omari', '7');
call create_reference_mapping_msf_internal('Dr. Ashraf Bustangi', '8');
call create_reference_mapping_msf_internal('Dr. Remy Zilliox', '9');
call create_reference_mapping_msf_internal('Dr.Ghassan S. Abu-Sittah', '10');
call create_reference_mapping_msf_internal('Fits anaesthesia criteria', '1');
call create_reference_mapping_msf_internal('R1D: does not fit anaesthesia criteria', '2');
call create_reference_mapping_msf_internal('Need complementary investigation', '3');
call create_reference_mapping_msf_internal('Dr. Hadeel Al-Ani', '1');
call create_reference_mapping_msf_internal('Dr. Ammar Sobhi Ahmad', '2');
call create_reference_mapping_msf_internal('Dr. Abdulraoof Al-Ahmad', '3');
call create_reference_mapping_msf_internal('P1: Time for modification', '1');
call create_reference_mapping_msf_internal('P2: Waiting for healing', '2');
call create_reference_mapping_msf_internal('P3: Surgery done recently', '3');
call create_reference_mapping_msf_internal('P4: Pre-op preparation in other structure', '4');
call create_reference_mapping_msf_internal('P5: Other reason', '5');
call create_reference_mapping_msf_internal('R1A: Out of criteria', '1');
call create_reference_mapping_msf_internal('R1B: Nothing to be done', '2');
call create_reference_mapping_msf_internal('R1C: Acceptable degree of function', '3');
call create_reference_mapping_msf_internal('FUP, Date of presentation at Followup', 'D_PRESENTATION');
call create_reference_mapping_msf_internal('FUP, Qualitative outcome-Union', 'OUT_UNION');
call create_reference_mapping_msf_internal('FUP, Qualitative outcome - Infection', 'OUT_INFECTION');
call create_reference_mapping_msf_internal('FUP, Qualitative outcome - SMFA', 'OUT_SMFA');
call create_reference_mapping_msf_internal('FUP, Outcomes for follow-up surgical validation', 'OUT_FUPVAL');
call create_reference_mapping_msf_internal('FUP, Time for next medical follow-up', 'TIME_FUP');
call create_reference_mapping_msf_internal('FUP, Date of next medical follow-up', 'D_FUP');
call create_reference_mapping_msf_internal('FUP, Type of medical investigations requested', 'TYPE_MEDINV');
call create_reference_mapping_msf_internal('FUP, Comments about next follow-up', 'COMMENTS_NEXT_FUP');
call create_reference_mapping_msf_internal('FUP, Comments about MBA', 'COMMENTS_MBA');
call create_reference_mapping_msf_internal('FUP, Dismissal reason', 'DISMISSAL_REASON');
call create_reference_mapping_msf_internal('FUP, Dismissal confirmed', 'CONF_DISMISSAL');
call create_reference_mapping_msf_internal('FUP, Comments about dismissal', 'COMMENTS_DISMISSAL');
call create_reference_mapping_msf_internal('FUP, Comments about Defaulter', 'COMMENTS_DEFAULTER');
call create_reference_mapping_msf_internal('FUP, Reason for re-admission', 'REASON_READMIN');
call create_reference_mapping_msf_internal('FUP, Priority', 'PRIORITY');
call create_reference_mapping_msf_internal('FUP, Name (s) of Surgeon 1', 'SURGEON');
call create_reference_mapping_msf_internal('FUP, Name (s) of Surgeon 2', 'SURGEON');
call create_reference_mapping_msf_internal('FUP, Does the Patient need Surgical Final Validation', 'NEEDFV');
call create_reference_mapping_msf_internal('FUP, Comments about further stage admission', 'COMMENTS_READMIN');
call create_reference_mapping_msf_internal('Bridging Callus', '1');
call create_reference_mapping_msf_internal('United', '2');
call create_reference_mapping_msf_internal('Non united', '3');
call create_reference_mapping_msf_internal('Infection', '1');
call create_reference_mapping_msf_internal('No infection', '2');
call create_reference_mapping_msf_internal('Pin tract infection', '3');
call create_reference_mapping_msf_internal('Done', '1');
call create_reference_mapping_msf_internal('Not Done', '0');
call create_reference_mapping_msf_internal('Continue under follow-up', '1');
call create_reference_mapping_msf_internal('MBA', '2');
call create_reference_mapping_msf_internal('Dismissal', '3');
call create_reference_mapping_msf_internal('Defaulter (D2)', '4');
call create_reference_mapping_msf_internal('Further stage admission', '5');
call create_reference_mapping_msf_internal('1 month', '1');
call create_reference_mapping_msf_internal('2 months', '2');
call create_reference_mapping_msf_internal('3 months', '3');
call create_reference_mapping_msf_internal('4 months', '4');
call create_reference_mapping_msf_internal('5 months', '5');
call create_reference_mapping_msf_internal('6 months', '6');
call create_reference_mapping_msf_internal('7 months', '7');
call create_reference_mapping_msf_internal('8 months', '8');
call create_reference_mapping_msf_internal('9 months', '9');
call create_reference_mapping_msf_internal('10 months', '10');
call create_reference_mapping_msf_internal('11 months', '11');
call create_reference_mapping_msf_internal('12 months', '12');
call create_reference_mapping_msf_internal('13 months', '13');
call create_reference_mapping_msf_internal('14 months', '14');
call create_reference_mapping_msf_internal('15 months', '15');
call create_reference_mapping_msf_internal('16 months', '16');
call create_reference_mapping_msf_internal('17 months', '17');
call create_reference_mapping_msf_internal('18 months', '18');
call create_reference_mapping_msf_internal('19 months', '19');
call create_reference_mapping_msf_internal('20 months', '20');
call create_reference_mapping_msf_internal('21 months', '21');
call create_reference_mapping_msf_internal('22 months', '22');
call create_reference_mapping_msf_internal('23 months', '23');
call create_reference_mapping_msf_internal('24 months', '24');
call create_reference_mapping_msf_internal('X-ray', '1');
call create_reference_mapping_msf_internal('Photo ', '2');
call create_reference_mapping_msf_internal('Video', '4');
call create_reference_mapping_msf_internal('Reports', '5');
call create_reference_mapping_msf_internal('Other Medical Investigation', '6');
call create_reference_mapping_msf_internal('R2A: operation in home country', '1');
call create_reference_mapping_msf_internal('R2B: refused treatment plan / to do FUP', '2');
call create_reference_mapping_msf_internal('R2C: refused to travel to Amman', '3');
call create_reference_mapping_msf_internal('Complementary surgery', '1');
call create_reference_mapping_msf_internal('Treatment of complication', '2');
call create_reference_mapping_msf_internal('New injury', '3');
call create_reference_mapping_msf_internal('FV, Date of Presentation', 'D_PRESENTATION');
call create_reference_mapping_msf_internal('FV, Outcomes FV', 'OUT_FV');
call create_reference_mapping_msf_internal('FV, Comments on FV', 'COMMENTS_FV');
call create_reference_mapping_msf_internal('FV, Expected Date of Arrival', 'D_EXP');
call create_reference_mapping_msf_internal('FV, Does the Patient need Accommodation?', 'ACCOM');
call create_reference_mapping_msf_internal('FV, Type of Admission Recommended', 'TYPE_ADMIS');
call create_reference_mapping_msf_internal('FV, Name (s) of Surgeon 1', 'SURGEON');
call create_reference_mapping_msf_internal('FV, Name (s) of Surgeon 2', 'SURGEON');
call create_reference_mapping_msf_internal('Accepted', '1');
call create_reference_mapping_msf_internal('Further Evaluation', '2');
call create_reference_mapping_msf_internal('Rejected', '4');
call create_reference_mapping_msf_internal('R2A : Surgery Outside', '5');
call create_reference_mapping_msf_internal('R2B: Refused Treatment or Follow-up', '6');
call create_reference_mapping_msf_internal('R2D: Refused to Undergo Surgery', '7');
call create_reference_mapping_msf_internal('Normal admission', '1');
call create_reference_mapping_msf_internal('Direct admission to Ward', '2');
call create_reference_mapping_msf_internal('VS, Date recorded', 'D_RECORDED');
call create_reference_mapping_msf_internal('Weight', 'WEIGHT');
call create_reference_mapping_msf_internal('Height', 'HEIGHT');
call create_reference_mapping_msf_internal('BMI', 'BMI');
call create_reference_mapping_msf_internal('VS, Respiratory Rate', 'RR');
call create_reference_mapping_msf_internal('VS, Temperature', 'TEMP');
call create_reference_mapping_msf_internal('VS, Pulse', 'PULSE');
call create_reference_mapping_msf_internal('VS, Systolic blood pressure', 'SBP');
call create_reference_mapping_msf_internal('VS, Diastolic blood pressure', 'DBP');
call create_reference_mapping_msf_internal('VS, Blood oxygen saturation', 'OXYGEN');
call create_reference_mapping_msf_internal('VS, Fasting', 'VS_FASTING');
call create_reference_mapping_msf_internal('VS, Random', 'VS_RANDOM');
call create_reference_mapping_msf_internal('VS, Comments about baseline vital signs', 'COMMENTS_VS');
call create_reference_mapping_msf_internal('SMH, Date of consultation', 'D_CONSULTATION');
call create_reference_mapping_msf_internal('SMH, Pain severity', 'PAIN');
call create_reference_mapping_msf_internal('SMH, Side of pain', 'P_SIDE');
call create_reference_mapping_msf_internal('SMH, Site of pain', 'P_SITE');
call create_reference_mapping_msf_internal('SMH, Site, Other', 'OTHER_P_SITE');
call create_reference_mapping_msf_internal('SMH, Number of wounds', 'NUM_WOUNDS');
call create_reference_mapping_msf_internal('SMH, Site', 'WOUND_SITE');
call create_reference_mapping_msf_internal('SMH, Description', 'DESC_WOUND');
call create_reference_mapping_msf_internal('SMH, Nursing notes', 'NOTES_NURS');
call create_reference_mapping_msf_internal('Right', '0');
call create_reference_mapping_msf_internal('Left', '1');
call create_reference_mapping_msf_internal('Site, Eye', '1');
call create_reference_mapping_msf_internal('Site, Ear', '2');
call create_reference_mapping_msf_internal('Site, Nose', '3');
call create_reference_mapping_msf_internal('Site, Mouth', '4');
call create_reference_mapping_msf_internal('Site, Cheek', '5');
call create_reference_mapping_msf_internal('Site, Chin', '6');
call create_reference_mapping_msf_internal('Site, Scalp', '7');
call create_reference_mapping_msf_internal('Site, Neck', '8');
call create_reference_mapping_msf_internal('Site, Face', '10');
call create_reference_mapping_msf_internal('Site, Finger', '11');
call create_reference_mapping_msf_internal('Site, Breast', '12');
call create_reference_mapping_msf_internal('Site, Trunk', '13');
call create_reference_mapping_msf_internal('Site, Groin', '14');
call create_reference_mapping_msf_internal('Site, Toe', '15');
call create_reference_mapping_msf_internal('Site, Shoulder', '16');
call create_reference_mapping_msf_internal('Site, Axilla', '17');
call create_reference_mapping_msf_internal('Site, Arm', '18');
call create_reference_mapping_msf_internal('Site, Elbow', '19');
call create_reference_mapping_msf_internal('Site, Forearm', '20');
call create_reference_mapping_msf_internal('Site, Wrist', '21');
call create_reference_mapping_msf_internal('Site, Hand', '22');
call create_reference_mapping_msf_internal('Site, Gluteal', '23');
call create_reference_mapping_msf_internal('Site, Hip', '24');
call create_reference_mapping_msf_internal('Site, Thigh', '25');
call create_reference_mapping_msf_internal('Site, Knee', '26');
call create_reference_mapping_msf_internal('Site, Leg', '27');
call create_reference_mapping_msf_internal('Site, Ankle', '28');
call create_reference_mapping_msf_internal('Site, Foot', '29');
call create_reference_mapping_msf_internal('Site, Iliac', '30');
call create_reference_mapping_msf_internal('Site, Femur', '31');
call create_reference_mapping_msf_internal('Site, Stump', '32');
call create_reference_mapping_msf_internal('Site, Other', '9');
call create_reference_mapping_msf_internal('HE, Date of consultation', 'D_CONSULTATION');
call create_reference_mapping_msf_internal('HE, Marital status', 'MARSTAT');
call create_reference_mapping_msf_internal('HE, Highest education level', 'EDUCATION');
call create_reference_mapping_msf_internal('HE, Pregnancy status', 'PREGNANCY ');
call create_reference_mapping_msf_internal('HE, Current smoker', 'SMOKING');
call create_reference_mapping_msf_internal('HE, Number of cigarettes per day', 'CIGPERDAY');
call create_reference_mapping_msf_internal('HE, Duration of smoking (in years)', 'DURATION_SMOK');
call create_reference_mapping_msf_internal('HE, Drug and Alcohol use', 'DRUG_ALC');
call create_reference_mapping_msf_internal('HE, External devices, present', 'EXDEVICE');
call create_reference_mapping_msf_internal('HE, Other type of external device', 'OTHER_EXDEVICE');
call create_reference_mapping_msf_internal('HE, Nutritional Assessment', 'NUTRI_ASS');
call create_reference_mapping_msf_internal('HE, Personal hygiene', 'PHYGIENE');
call create_reference_mapping_msf_internal('HE, Education learning needs', 'LEARN_NEEDS');
call create_reference_mapping_msf_internal('HE, Referral care Plan', 'REFERRAL_PLAN');
call create_reference_mapping_msf_internal('Single', '1');
call create_reference_mapping_msf_internal('Married', '2');
call create_reference_mapping_msf_internal('Divorced', '3');
call create_reference_mapping_msf_internal('Widowed', '4');
call create_reference_mapping_msf_internal('Child', '5');
call create_reference_mapping_msf_internal('No formal education', '1');
call create_reference_mapping_msf_internal('Primary school education', '2');
call create_reference_mapping_msf_internal('Secondary school education', '3');
call create_reference_mapping_msf_internal('University', '4');
call create_reference_mapping_msf_internal('Unknown', '99');
call create_reference_mapping_msf_internal('In the past', '1');
call create_reference_mapping_msf_internal('Currently', '2');
call create_reference_mapping_msf_internal('Never', '0');
call create_reference_mapping_msf_internal('None', '0');
call create_reference_mapping_msf_internal('Ex-fix', '1');
call create_reference_mapping_msf_internal('Foley catheter', '2');
call create_reference_mapping_msf_internal('Condom catheter', '3');
call create_reference_mapping_msf_internal('Colostomy bag', '4');
call create_reference_mapping_msf_internal('Big tube', '5');
call create_reference_mapping_msf_internal('Tracheostomy', '6');
call create_reference_mapping_msf_internal('Regular', '1');
call create_reference_mapping_msf_internal('Low salt', '2');
call create_reference_mapping_msf_internal('High protein', '3');
call create_reference_mapping_msf_internal('Diabetic diet', '4');