call create_reference_mapping_msf_internal('MH, Name of MLO', 'MLO');
call create_reference_mapping_msf_internal('MH, Network Area', 'NETWORK');
call create_reference_mapping_msf_internal('MH, Referred by', 'REFERRED');
call create_reference_mapping_msf_internal('MH, Date of injury', 'D_INJURY');
call create_reference_mapping_msf_internal('MH, Cause of injury', 'C_INJURY');
call create_reference_mapping_msf_internal('MH, Patient General Condition', 'PGENCON');
call create_reference_mapping_msf_internal('MH, If caretaker is needed, why?', 'NEEDCT');
call create_reference_mapping_msf_internal('Dr. Aziz Abu Azizeh', '1');
call create_reference_mapping_msf_internal('Dr. Medya Rasheed', '2');
call create_reference_mapping_msf_internal('Dr. Abdulhmeed Qaradaya', '3');
call create_reference_mapping_msf_internal('Dr. Feras Nasr', '4');
call create_reference_mapping_msf_internal('Dr. Wisam Hussam', '5');
call create_reference_mapping_msf_internal('Dr. Mohammed Hamed', '6');
call create_reference_mapping_msf_internal('Dr. Ali Arkan', '7');
call create_reference_mapping_msf_internal('Dr. Hozak Zaheer', '8');
call create_reference_mapping_msf_internal('Dr. Anas Ahmed', '9');
call create_reference_mapping_msf_internal('Dr. Israa Al Jumaily', '10');
call create_reference_mapping_msf_internal('Dr. Haider Abdulkareem Qasim', '11');
call create_reference_mapping_msf_internal('Dr. Nadhum Duriad Nadhum', '12');
call create_reference_mapping_msf_internal('Dr. Omar Adil Alani', '13');
call create_reference_mapping_msf_internal('Dr. Aso Sulaiman Qahraman', '14');
call create_reference_mapping_msf_internal('Dr. Ehsan Al Masri', '15');
call create_reference_mapping_msf_internal('Dr. Meayada Ali Obeid', '16');
call create_reference_mapping_msf_internal('Dr. Wafa Al-Shawa', '17');
call create_reference_mapping_msf_internal('Aden Network', '1');
call create_reference_mapping_msf_internal('Gaza Network', '2');
call create_reference_mapping_msf_internal('Al Anbar Network', '3');
call create_reference_mapping_msf_internal('Baghdad Network', '4');
call create_reference_mapping_msf_internal('Erbil Network', '5');
call create_reference_mapping_msf_internal('Kirkuk Network', '6');
call create_reference_mapping_msf_internal('Diyala Network', '7');
call create_reference_mapping_msf_internal('Dohuk Network', '8');
call create_reference_mapping_msf_internal('Karbala Network', '9');
call create_reference_mapping_msf_internal('Najaf Network', '10');
call create_reference_mapping_msf_internal('Nineveh Network', '11');
call create_reference_mapping_msf_internal('Salahadin Network', '12');
call create_reference_mapping_msf_internal('Sulaymaniyah Network', '13');
call create_reference_mapping_msf_internal('Kilis Network', '14');
call create_reference_mapping_msf_internal('Sanliurfa Network', '15');
call create_reference_mapping_msf_internal('Gaziantep Network', '16');
call create_reference_mapping_msf_internal('Hatay Network', '17');
call create_reference_mapping_msf_internal("Sana'a Network", '18');
call create_reference_mapping_msf_internal('Jordan Network', '19');
call create_reference_mapping_msf_internal('Blunt - Road traffic crash (War)', '1');
call create_reference_mapping_msf_internal('Blunt - Collapsed buildings and falls', '2');
call create_reference_mapping_msf_internal('Blunt - Explosions and anti-tank mines', '3');
call create_reference_mapping_msf_internal('Blunt - Beatings', '4');
call create_reference_mapping_msf_internal('Penetrating - Fragment wounds', '5');
call create_reference_mapping_msf_internal('Penetrating - Bullet wounds', '6');
call create_reference_mapping_msf_internal("Penetrating - Cut wounds 'arme blanche'", '7');
call create_reference_mapping_msf_internal('Anti-personal landmine wounds', '8');
call create_reference_mapping_msf_internal('Explosive blast injuries', '10');
call create_reference_mapping_msf_internal('Burns', '11');
call create_reference_mapping_msf_internal('Non-conventional weapons', '12');
call create_reference_mapping_msf_internal('Road traffic accident', '13');
call create_reference_mapping_msf_internal('Domestic accident', '14');
call create_reference_mapping_msf_internal('Other', '9');
call create_reference_mapping_msf_internal('Walking alone', '1');
call create_reference_mapping_msf_internal('Crutches', '2');
call create_reference_mapping_msf_internal('Walking frame', '3');
call create_reference_mapping_msf_internal('Walking cane', '4');
call create_reference_mapping_msf_internal('wheelchair', '5');
call create_reference_mapping_msf_internal('Bedridden', '6');
call create_reference_mapping_msf_internal('Under 18 years', '1');
call create_reference_mapping_msf_internal('Female above 18 Years w/o disability', '2');
call create_reference_mapping_msf_internal('Functional disability', '3');
call create_reference_mapping_msf_internal('Psycho-social disability', '4');
call create_reference_mapping_msf_internal('FSTG, Type of medical information received', 'TYPE_MEDINFO');
call create_reference_mapping_msf_internal('FSTG, Date received', 'D_RECEIVED');
call create_reference_mapping_msf_internal('FSTG, Is the medical file complete?', 'COMPLETE_FILE');
call create_reference_mapping_msf_internal('FSTG, Document(s) needed to be complete', 'NEEDED_DOCS');
call create_reference_mapping_msf_internal('FSTG, Specialty determined by MLO', 'SPECIALTY');
call create_reference_mapping_msf_internal('Stage', 'PTSTAGE');
call create_reference_mapping_msf_internal('FSTG, Date of presentation at 1st stage', 'D_PRESENTATION');
call create_reference_mapping_msf_internal('FSTG, Outcomes for 1st stage surgical validation', 'OUT_1STSURG');
call create_reference_mapping_msf_internal('FSTG, Priority', 'PRIORITY');
call create_reference_mapping_msf_internal('FSTG, Name (s) of Surgeon 1', 'SURGEON');
call create_reference_mapping_msf_internal('FSTG, Name (s) of Surgeon 2', 'SURGEON');
call create_reference_mapping_msf_internal('FSTG, Does the Patient need Surgical Final Validation', 'NEEDFV');
call create_reference_mapping_msf_internal('FSTG, Comments', 'COMMENTS');
call create_reference_mapping_msf_internal('FSTG, Outcomes for 1st stage Anaesthesia validation', 'OUT_1STANAESTH');
call create_reference_mapping_msf_internal('FSTG, Name (s) of Anaesthetist', 'ANAESTHETIST');
call create_reference_mapping_msf_internal('FSTG, Comments about Anaesthesia validation', 'COMMENTS');
call create_reference_mapping_msf_internal('FSTG, Postpone reason', 'PP_REASON');
call create_reference_mapping_msf_internal('FSTG, Comments about postpone reason', 'COMMENTS_PP');
call create_reference_mapping_msf_internal('FSTG, Medical file to be submitted again by', 'DATE_RESUB');
call create_reference_mapping_msf_internal('FSTG, Type of medical information needed for next submission', 'TYPE_MEDINFO_RESUB');
call create_reference_mapping_msf_internal('FST, Type of medical information needed for next submission', 'TYPE_MEDINFO_RESUB');
call create_reference_mapping_msf_internal('FSTG, Refused Reason', 'REFUSED_REASON');
call create_reference_mapping_msf_internal('FSTG, Comments about refusal', 'COMMENTS_REFUSAL');
call create_reference_mapping_msf_internal('New medical file', '1');
call create_reference_mapping_msf_internal('Updated Medical file', '2');
call create_reference_mapping_msf_internal('Anaesthesia update', '3');
call create_reference_mapping_msf_internal('Yes', '1');
call create_reference_mapping_msf_internal('No', '0');
call create_reference_mapping_msf_internal('Orthopedic', '1');
call create_reference_mapping_msf_internal('Plastic', '2');
call create_reference_mapping_msf_internal('Maxillofacial', '3');
call create_reference_mapping_msf_internal('Valid', '1');
call create_reference_mapping_msf_internal('Postponed', '2');
call create_reference_mapping_msf_internal('More Information', '3');
call create_reference_mapping_msf_internal('Refused', '4');
call create_reference_mapping_msf_internal('Low', '1');
call create_reference_mapping_msf_internal('Moderate', '2');
call create_reference_mapping_msf_internal('High', '3');
call create_reference_mapping_msf_internal('Urgent', '4');
call create_reference_mapping_msf_internal('Dr. Ali Al-Ani', '1');
call create_reference_mapping_msf_internal('Dr. Sofian Al-Qassab', '2');
call create_reference_mapping_msf_internal('Dr. Hanna Janho', '3');
call create_reference_mapping_msf_internal('Dr. Ashraf Nabhan', '4');
call create_reference_mapping_msf_internal('Dr. Rasheed Al Samerai', '5');
call create_reference_mapping_msf_internal('Dr. Muckhaled Naseef', '6');
call create_reference_mapping_msf_internal('Dr. Nasr Al-Omari', '7');
call create_reference_mapping_msf_internal('Dr. Ashraf Bustangi', '8');
call create_reference_mapping_msf_internal('Dr. Remy Zilliox', '9');
call create_reference_mapping_msf_internal('Dr.Ghassan S. Abu-Sittah', '10');
call create_reference_mapping_msf_internal('Fits anaesthesia criteria', '1');
call create_reference_mapping_msf_internal('R1D: does not fit anaesthesia criteria', '2');
call create_reference_mapping_msf_internal('Need complementary investigation', '3');
call create_reference_mapping_msf_internal('Dr. Hadeel Al-Ani', '1');
call create_reference_mapping_msf_internal('Dr. Ammar Sobhi Ahmad', '2');
call create_reference_mapping_msf_internal('Dr. Abdulraoof Al-Ahmad', '3');
call create_reference_mapping_msf_internal('P1: Time for modification', '1');
call create_reference_mapping_msf_internal('P2: Waiting for healing', '2');
call create_reference_mapping_msf_internal('P3: Surgery done recently', '3');
call create_reference_mapping_msf_internal('P4: Pre-op preparation in other structure', '4');
call create_reference_mapping_msf_internal('P5: Other reason', '5');
call create_reference_mapping_msf_internal('R1A: Out of criteria', '1');
call create_reference_mapping_msf_internal('R1B: Nothing to be done', '2');
call create_reference_mapping_msf_internal('R1C: Acceptable degree of function', '3');
call create_reference_mapping_msf_internal('FUP, Date of presentation at Followup', 'D_PRESENTATION');
call create_reference_mapping_msf_internal('FUP, Qualitative outcome-Union', 'OUT_UNION');
call create_reference_mapping_msf_internal('FUP, Qualitative outcome - Infection', 'OUT_INFECTION');
call create_reference_mapping_msf_internal('FUP, Qualitative outcome - SMFA', 'OUT_SMFA');
call create_reference_mapping_msf_internal('FUP, Outcomes for follow-up surgical validation', 'OUT_FUPVAL');
call create_reference_mapping_msf_internal('FUP, Time for next medical follow-up', 'TIME_FUP');
call create_reference_mapping_msf_internal('FUP, Date of next medical follow-up', 'D_FUP');
call create_reference_mapping_msf_internal('FUP, Type of medical investigations requested', 'TYPE_MEDINV');
call create_reference_mapping_msf_internal('FUP, Comments about next follow-up', 'COMMENTS_NEXT_FUP');
call create_reference_mapping_msf_internal('FUP, Comments about MBA', 'COMMENTS_MBA');
call create_reference_mapping_msf_internal('FUP, Dismissal reason', 'DISMISSAL_REASON');
call create_reference_mapping_msf_internal('FUP, Dismissal confirmed', 'CONF_DISMISSAL');
call create_reference_mapping_msf_internal('FUP, Comments about dismissal', 'COMMENTS_DISMISSAL');
call create_reference_mapping_msf_internal('FUP, Comments about Defaulter', 'COMMENTS_DEFAULTER');
call create_reference_mapping_msf_internal('FUP, Reason for re-admission', 'REASON_READMIN');
call create_reference_mapping_msf_internal('FUP, Priority', 'PRIORITY');
call create_reference_mapping_msf_internal('FUP, Name (s) of Surgeon 1', 'SURGEON');
call create_reference_mapping_msf_internal('FUP, Name (s) of Surgeon 2', 'SURGEON');
call create_reference_mapping_msf_internal('FUP, Does the Patient need Surgical Final Validation', 'NEEDFV');
call create_reference_mapping_msf_internal('FUP, Comments about further stage admission', 'COMMENTS_READMIN');
call create_reference_mapping_msf_internal('Bridging Callus', '1');
call create_reference_mapping_msf_internal('United', '2');
call create_reference_mapping_msf_internal('Non united', '3');
call create_reference_mapping_msf_internal('Infection', '1');
call create_reference_mapping_msf_internal('No infection', '2');
call create_reference_mapping_msf_internal('Pin tract infection', '3');
call create_reference_mapping_msf_internal('Done', '1');
call create_reference_mapping_msf_internal('Not Done', '0');
call create_reference_mapping_msf_internal('Continue under follow-up', '1');
call create_reference_mapping_msf_internal('MBA', '2');
call create_reference_mapping_msf_internal('Dismissal', '3');
call create_reference_mapping_msf_internal('Defaulter (D2)', '4');
call create_reference_mapping_msf_internal('Further stage admission', '5');
call create_reference_mapping_msf_internal('1 month', '1');
call create_reference_mapping_msf_internal('2 months', '2');
call create_reference_mapping_msf_internal('3 months', '3');
call create_reference_mapping_msf_internal('4 months', '4');
call create_reference_mapping_msf_internal('5 months', '5');
call create_reference_mapping_msf_internal('6 months', '6');
call create_reference_mapping_msf_internal('7 months', '7');
call create_reference_mapping_msf_internal('8 months', '8');
call create_reference_mapping_msf_internal('9 months', '9');
call create_reference_mapping_msf_internal('10 months', '10');
call create_reference_mapping_msf_internal('11 months', '11');
call create_reference_mapping_msf_internal('12 months', '12');
call create_reference_mapping_msf_internal('13 months', '13');
call create_reference_mapping_msf_internal('14 months', '14');
call create_reference_mapping_msf_internal('15 months', '15');
call create_reference_mapping_msf_internal('16 months', '16');
call create_reference_mapping_msf_internal('17 months', '17');
call create_reference_mapping_msf_internal('18 months', '18');
call create_reference_mapping_msf_internal('19 months', '19');
call create_reference_mapping_msf_internal('20 months', '20');
call create_reference_mapping_msf_internal('21 months', '21');
call create_reference_mapping_msf_internal('22 months', '22');
call create_reference_mapping_msf_internal('23 months', '23');
call create_reference_mapping_msf_internal('24 months', '24');
call create_reference_mapping_msf_internal('X-ray', '1');
call create_reference_mapping_msf_internal('Photo ', '2');
call create_reference_mapping_msf_internal('Video', '4');
call create_reference_mapping_msf_internal('Reports', '5');
call create_reference_mapping_msf_internal('Other Medical Investigation', '6');
call create_reference_mapping_msf_internal('R2A: operation in home country', '1');
call create_reference_mapping_msf_internal('R2B: refused treatment plan / to do FUP', '2');
call create_reference_mapping_msf_internal('R2C: refused to travel to Amman', '3');
call create_reference_mapping_msf_internal('Complementary surgery', '1');
call create_reference_mapping_msf_internal('Treatment of complication', '2');
call create_reference_mapping_msf_internal('New injury', '3');
call create_reference_mapping_msf_internal('FV, Date of Presentation', 'D_PRESENTATION');
call create_reference_mapping_msf_internal('FV, Outcomes FV', 'OUT_FV');
call create_reference_mapping_msf_internal('FV, Comments on FV', 'COMMENTS_FV');
call create_reference_mapping_msf_internal('FV, Expected Date of Arrival', 'D_EXP');
call create_reference_mapping_msf_internal('FV, Does the Patient need Accommodation?', 'ACCOM');
call create_reference_mapping_msf_internal('FV, Type of Admission Recommended', 'TYPE_ADMIS');
call create_reference_mapping_msf_internal('FV, Name (s) of Surgeon 1', 'SURGEON');
call create_reference_mapping_msf_internal('FV, Name (s) of Surgeon 2', 'SURGEON');
call create_reference_mapping_msf_internal('Accepted', '1');
call create_reference_mapping_msf_internal('Further Evaluation', '2');
call create_reference_mapping_msf_internal('Rejected', '4');
call create_reference_mapping_msf_internal('R2A : Surgery Outside', '5');
call create_reference_mapping_msf_internal('R2B: Refused Treatment or Follow-up', '6');
call create_reference_mapping_msf_internal('R2D: Refused to Undergo Surgery', '7');
call create_reference_mapping_msf_internal('Normal admission', '1');
call create_reference_mapping_msf_internal('Direct admission to Ward', '2');
call create_reference_mapping_msf_internal('VS, Date recorded', 'D_RECORDED');
call create_reference_mapping_msf_internal('Weight', 'WEIGHT');
call create_reference_mapping_msf_internal('Height', 'HEIGHT');
call create_reference_mapping_msf_internal('BMI', 'BMI');
call create_reference_mapping_msf_internal('VS, Respiratory Rate', 'RR');
call create_reference_mapping_msf_internal('VS, Temperature', 'TEMP');
call create_reference_mapping_msf_internal('VS, Pulse', 'PULSE');
call create_reference_mapping_msf_internal('VS, Systolic blood pressure', 'SBP');
call create_reference_mapping_msf_internal('VS, Diastolic blood pressure', 'DBP');
call create_reference_mapping_msf_internal('VS, Blood oxygen saturation', 'OXYGEN');
call create_reference_mapping_msf_internal('VS, Fasting', 'VS_FASTING');
call create_reference_mapping_msf_internal('VS, Random', 'VS_RANDOM');
call create_reference_mapping_msf_internal('VS, Comments about baseline vital signs', 'COMMENTS_VS');
call create_reference_mapping_msf_internal('SMH, Date of consultation', 'D_CONSULTATION');
call create_reference_mapping_msf_internal('SMH, Pain severity', 'PAIN');
call create_reference_mapping_msf_internal('SMH, Side of pain', 'P_SIDE');
call create_reference_mapping_msf_internal('SMH, Site of pain', 'P_SITE');
call create_reference_mapping_msf_internal('SMH, Site, Other', 'OTHER_P_SITE');
call create_reference_mapping_msf_internal('SMH, Number of wounds', 'NUM_WOUNDS');
call create_reference_mapping_msf_internal('SMH, Site', 'WOUND_SITE');
call create_reference_mapping_msf_internal('SMH, Description', 'DESC_WOUND');
call create_reference_mapping_msf_internal('SMH, Nursing notes', 'NOTES_NURS');
call create_reference_mapping_msf_internal('Right', '0');
call create_reference_mapping_msf_internal('Left', '1');
call create_reference_mapping_msf_internal('Site, Eye', '1');
call create_reference_mapping_msf_internal('Site, Ear', '2');
call create_reference_mapping_msf_internal('Site, Nose', '3');
call create_reference_mapping_msf_internal('Site, Mouth', '4');
call create_reference_mapping_msf_internal('Site, Cheek', '5');
call create_reference_mapping_msf_internal('Site, Chin', '6');
call create_reference_mapping_msf_internal('Site, Scalp', '7');
call create_reference_mapping_msf_internal('Site, Neck', '8');
call create_reference_mapping_msf_internal('Site, Face', '10');
call create_reference_mapping_msf_internal('Site, Finger', '11');
call create_reference_mapping_msf_internal('Site, Breast', '12');
call create_reference_mapping_msf_internal('Site, Trunk', '13');
call create_reference_mapping_msf_internal('Site, Groin', '14');
call create_reference_mapping_msf_internal('Site, Toe', '15');
call create_reference_mapping_msf_internal('Site, Shoulder', '16');
call create_reference_mapping_msf_internal('Site, Axilla', '17');
call create_reference_mapping_msf_internal('Site, Arm', '18');
call create_reference_mapping_msf_internal('Site, Elbow', '19');
call create_reference_mapping_msf_internal('Site, Forearm', '20');
call create_reference_mapping_msf_internal('Site, Wrist', '21');
call create_reference_mapping_msf_internal('Site, Hand', '22');
call create_reference_mapping_msf_internal('Site, Gluteal', '23');
call create_reference_mapping_msf_internal('Site, Hip', '24');
call create_reference_mapping_msf_internal('Site, Thigh', '25');
call create_reference_mapping_msf_internal('Site, Knee', '26');
call create_reference_mapping_msf_internal('Site, Leg', '27');
call create_reference_mapping_msf_internal('Site, Ankle', '28');
call create_reference_mapping_msf_internal('Site, Foot', '29');
call create_reference_mapping_msf_internal('Site, Iliac', '30');
call create_reference_mapping_msf_internal('Site, Femur', '31');
call create_reference_mapping_msf_internal('Site, Stump', '32');
call create_reference_mapping_msf_internal('Site, Other', '9');
call create_reference_mapping_msf_internal('HE, Date of consultation', 'D_CONSULTATION');
call create_reference_mapping_msf_internal('HE, Marital status', 'MARSTAT');
call create_reference_mapping_msf_internal('HE, Highest education level', 'EDUCATION');
call create_reference_mapping_msf_internal('HE, Pregnancy status', 'PREGNANCY ');
call create_reference_mapping_msf_internal('HE, Current smoker', 'SMOKING');
call create_reference_mapping_msf_internal('HE, Number of cigarettes per day', 'CIGPERDAY');
call create_reference_mapping_msf_internal('HE, Duration of smoking (in years)', 'DURATION_SMOK');
call create_reference_mapping_msf_internal('HE, Drug and Alcohol use', 'DRUG_ALC');
call create_reference_mapping_msf_internal('HE, External devices, present', 'EXDEVICE');
call create_reference_mapping_msf_internal('HE, Other type of external device', 'OTHER_EXDEVICE');
call create_reference_mapping_msf_internal('HE, Nutritional Assessment', 'NUTRI_ASS');
call create_reference_mapping_msf_internal('HE, Personal hygiene', 'PHYGIENE');
call create_reference_mapping_msf_internal('HE, Education learning needs', 'LEARN_NEEDS');
call create_reference_mapping_msf_internal('HE, Referral care Plan', 'REFERRAL_PLAN');
call create_reference_mapping_msf_internal('Single', '1');
call create_reference_mapping_msf_internal('Married', '2');
call create_reference_mapping_msf_internal('Divorced', '3');
call create_reference_mapping_msf_internal('Widowed', '4');
call create_reference_mapping_msf_internal('Child', '5');
call create_reference_mapping_msf_internal('No formal education', '1');
call create_reference_mapping_msf_internal('Primary school education', '2');
call create_reference_mapping_msf_internal('Secondary school education', '3');
call create_reference_mapping_msf_internal('University', '4');
call create_reference_mapping_msf_internal('Unknown', '99');
call create_reference_mapping_msf_internal('In the past', '1');
call create_reference_mapping_msf_internal('Currently', '2');
call create_reference_mapping_msf_internal('Never', '0');
call create_reference_mapping_msf_internal('None', '0');
call create_reference_mapping_msf_internal('Ex-fix', '1');
call create_reference_mapping_msf_internal('Foley catheter', '2');
call create_reference_mapping_msf_internal('Condom catheter', '3');
call create_reference_mapping_msf_internal('Colostomy bag', '4');
call create_reference_mapping_msf_internal('Big tube', '5');
call create_reference_mapping_msf_internal('Tracheostomy', '6');
call create_reference_mapping_msf_internal('Regular', '1');
call create_reference_mapping_msf_internal('Low salt', '2');
call create_reference_mapping_msf_internal('High protein', '3');
call create_reference_mapping_msf_internal('Diabetic diet', '4');
call create_reference_mapping_msf_internal('MD, Date of consultation', 'D_CONSULTATION');
call create_reference_mapping_msf_internal('MD, Reason for admission to program', 'AD_REASON');
call create_reference_mapping_msf_internal('MD, History of present illness', 'HPI');
call create_reference_mapping_msf_internal('MD, Medical History', 'MEDHX');
call create_reference_mapping_msf_internal('MD, Other medical problems', 'OTHER_MEDHX');
call create_reference_mapping_msf_internal('MD, History of Allergy', 'HXALLERGY');
call create_reference_mapping_msf_internal('MD, Comments about allergy', 'COMMENTS_ALLERGY');
call create_reference_mapping_msf_internal('MD, Currently taking medication', 'CURR_MEDS');
call create_reference_mapping_msf_internal('MD, Type of medication', 'TYPE_CURRMEDS');
call create_reference_mapping_msf_internal('MD, Dose and frequency', 'CURRMEDS_DOSEFX');
call create_reference_mapping_msf_internal('MD, Date of last dose', 'CURRMEDS_LASTD');
call create_reference_mapping_msf_internal('MD, Function of injured part', 'FUNCTION');
call create_reference_mapping_msf_internal('MD, Sensation of injured part', 'SENSATION');
call create_reference_mapping_msf_internal('MD, History of previous surgery', 'SURGHX');
call create_reference_mapping_msf_internal('MD, Procedures performed outside AMH', 'PROC_HX');
call create_reference_mapping_msf_internal('MD, Site of procedure', 'SITE_PROC_HX');
call create_reference_mapping_msf_internal('MD, Side of procedure', 'SIDE_PROC_HX');
call create_reference_mapping_msf_internal('MD, Comment of procedure', 'COMMENTS_PROC_HX');
call create_reference_mapping_msf_internal('MD, Date of procedure', 'D_PROC_HX');
call create_reference_mapping_msf_internal('MD, Type of previous fixation', 'TYPE_FIX');
call create_reference_mapping_msf_internal('MD, Type of internal fixation', 'TYPE_INT_FIX');
call create_reference_mapping_msf_internal('MD, Duration of External fixation', 'DUR_EX_FIX');
call create_reference_mapping_msf_internal('MD, Other type of fixation', 'FIX_OTHER');
call create_reference_mapping_msf_internal('MD, HIstory of infection', 'HXINFECTION');
call create_reference_mapping_msf_internal('MD, Comments about previous infection', 'COMMENTS_HXINFECTION');
call create_reference_mapping_msf_internal('MD, Discharging sinus', 'DISCHARG_SINUS');
call create_reference_mapping_msf_internal('MD, Duration of discharging sinus', 'DUR_DISCHARGESINUS');
call create_reference_mapping_msf_internal('MD, Bone Loss', 'BONELOSS');
call create_reference_mapping_msf_internal('MD, Cm of bone loss', 'CM_BONELOSS');
call create_reference_mapping_msf_internal('MD, United fracture', 'UNITEDFX');
call create_reference_mapping_msf_internal('MD, Shortening', 'SHORTENING');
call create_reference_mapping_msf_internal('MD, Cm of shortening', 'CM_SHORTENING');
call create_reference_mapping_msf_internal('MD, Review of systems, general', 'ROS_GEN');
call create_reference_mapping_msf_internal('MD, Description and duration of symptom (general)', 'DESC_GEN');
call create_reference_mapping_msf_internal('MD, Other ROS general symptoms', 'OTHER_ROS_GEN');
call create_reference_mapping_msf_internal('MD, Review of systems, cardiopulmonary', 'ROS_CARDIOPUL');
call create_reference_mapping_msf_internal('MD, Description and duration of symptom (cardiopulmonary)', 'DESC_CARDIOPUL');
call create_reference_mapping_msf_internal('MD, Other ROS cardiopulmonary symptoms', 'OTHER_ROS_CARDIOPUL');
call create_reference_mapping_msf_internal('MD, Review of systems, gastrointestinal', 'ROS_GI');
call create_reference_mapping_msf_internal('MD, Description and duration of symptom (gastrointestinal)', 'DESC_GI');
call create_reference_mapping_msf_internal('MD, Other ROS gastrointestinal symptoms', 'OTHER_ROS_GI');
call create_reference_mapping_msf_internal('MD, Review of systems, genitourinary', 'ROS_GU');
call create_reference_mapping_msf_internal('MD, Description and duration of symptom (genitourinary)', 'DESC_GU');
call create_reference_mapping_msf_internal('MD, Other ROS genitourinary symptoms', 'OTHER_ROS_GU');
call create_reference_mapping_msf_internal('MD, Review of systems, central nervous system', 'ROS_CNS');
call create_reference_mapping_msf_internal('MD, Description and duration of symptom (central nervous system)', 'DESC_CNS');
call create_reference_mapping_msf_internal('MD, Other ROS central nervous system symptoms', 'OTHER_ROS_CNS');
call create_reference_mapping_msf_internal('MD, Review of systems, HEENT', 'ROS_HEENT');
call create_reference_mapping_msf_internal('MD, Description and duration of symptom (HEENT)', 'DESC_HEENT');
call create_reference_mapping_msf_internal('MD, Other ROS HEENT symptoms', 'OTHER_ROS_HEENT');
call create_reference_mapping_msf_internal('MD, Review of systems, musculoskeletal', 'ROS_MSK');
call create_reference_mapping_msf_internal('MD, Description and duration of symptom (musculoskeletal)', 'DESC_MSK');
call create_reference_mapping_msf_internal('MD, Other ROS musculoskeletal symptoms', 'OTHER_ROS_MSK');
call create_reference_mapping_msf_internal('None', '0');
call create_reference_mapping_msf_internal('Hypertension', '1');
call create_reference_mapping_msf_internal('Palpitations', '2');
call create_reference_mapping_msf_internal('Dyspnea', '3');
call create_reference_mapping_msf_internal('Asthma', '4');
call create_reference_mapping_msf_internal('Tuberculosis', '5');
call create_reference_mapping_msf_internal('Diabetes mellitus', '6');
call create_reference_mapping_msf_internal('Angina', '7');
call create_reference_mapping_msf_internal('Peptic Ulcer', '8');
call create_reference_mapping_msf_internal('Jaundice', '10');
call create_reference_mapping_msf_internal('Epilepsy', '11');
call create_reference_mapping_msf_internal('Hepatitis', '12');
call create_reference_mapping_msf_internal('Kidney problems', '13');
call create_reference_mapping_msf_internal('High cholesterol', '15');
call create_reference_mapping_msf_internal('COPD', '14');
call create_reference_mapping_msf_internal('Drugs', '1');
call create_reference_mapping_msf_internal('Food', '2');
call create_reference_mapping_msf_internal('Normal', '1');
call create_reference_mapping_msf_internal('Good', '2');
call create_reference_mapping_msf_internal('Visible deformity', '3');
call create_reference_mapping_msf_internal('Limitation of function', '4');
call create_reference_mapping_msf_internal('Reduced (Regional)', '2');
call create_reference_mapping_msf_internal('Senseless', '3');
call create_reference_mapping_msf_internal('Advancement of flap', '1');
call create_reference_mapping_msf_internal('Amputation', '2');
call create_reference_mapping_msf_internal('Reamputation of stump', '3');
call create_reference_mapping_msf_internal('Revision of amputation stump', '4');
call create_reference_mapping_msf_internal('Secondary closure of stump', '5');
call create_reference_mapping_msf_internal('Trimming of stump', '6');
call create_reference_mapping_msf_internal('Application of an external fixation device', '7');
call create_reference_mapping_msf_internal('Application of back slab', '8');
call create_reference_mapping_msf_internal('Application of cast', '9');
call create_reference_mapping_msf_internal('Arthrodesis', '10');
call create_reference_mapping_msf_internal('Arthrolysis', '11');
call create_reference_mapping_msf_internal('Axial Flap', '12');
call create_reference_mapping_msf_internal('Biopsy of bone', '13');
call create_reference_mapping_msf_internal('Biopsy of joint structure', '14');
call create_reference_mapping_msf_internal('Bone graft', '15');
call create_reference_mapping_msf_internal('Bone lengthening', '16');
call create_reference_mapping_msf_internal('Capsulectomy procedure', '17');
call create_reference_mapping_msf_internal('Change of dressing', '18');
call create_reference_mapping_msf_internal('Change or adjustment of external fixation device / Management of an external fixation device', '19');
call create_reference_mapping_msf_internal('Closed biopsy of skin and subcutaneous cell tissue, site not specified', '20');
call create_reference_mapping_msf_internal('Commissuroplasty', '21');
call create_reference_mapping_msf_internal('Coronoidectomy', '22');
call create_reference_mapping_msf_internal('Delayed suture of wound', '23');
call create_reference_mapping_msf_internal('Dermabrasion', '24');
call create_reference_mapping_msf_internal('Division of flap', '25');
call create_reference_mapping_msf_internal('Excision of peripheral neuroma', '26');
call create_reference_mapping_msf_internal('Excisional debridement of wound, infection, or burn', '27');
call create_reference_mapping_msf_internal('Exploration of nerve', '28');
call create_reference_mapping_msf_internal('Fascial sling for facial weakness', '29');
call create_reference_mapping_msf_internal('Filling of segmental defect by bone transport', '30');
call create_reference_mapping_msf_internal('Fixation of fracture using pins', '31');
call create_reference_mapping_msf_internal('Frontal sinusectomy', '32');
call create_reference_mapping_msf_internal('Full thickness skin graft', '33');
call create_reference_mapping_msf_internal('Grafting of cartilage', '34');
call create_reference_mapping_msf_internal('Injection of steroid', '35');
call create_reference_mapping_msf_internal('Insertion of peripherally inserted central catheter', '36');
call create_reference_mapping_msf_internal('Insertion of tissue expander', '37');
call create_reference_mapping_msf_internal('Insertion or replacement of (cement) spacer', '38');
call create_reference_mapping_msf_internal('Insertion/Removal of Drain or Tube', '39');
call create_reference_mapping_msf_internal('Integra skin graft', '40');
call create_reference_mapping_msf_internal('Internal fixation using intramedullary nail', '41');
call create_reference_mapping_msf_internal('Internal fixation using plate', '42');
call create_reference_mapping_msf_internal('Internal fixation using screw', '43');
call create_reference_mapping_msf_internal('Internal fixation using wire', '44');
call create_reference_mapping_msf_internal('Regional flap', '45');
call create_reference_mapping_msf_internal('Joint capsulodesis', '46');
call create_reference_mapping_msf_internal('Local rotation flap', '47');
call create_reference_mapping_msf_internal('Local subcutaneous pedicled V-Y flap', '48');
call create_reference_mapping_msf_internal('Lysis of adhesions of tendon / tenolysis', '49');
call create_reference_mapping_msf_internal('Manipulation under anesthesia', '50');
call create_reference_mapping_msf_internal('Nerve block', '51');
call create_reference_mapping_msf_internal('Nerve graft', '52');
call create_reference_mapping_msf_internal('Neurorrhaphy / suture of nerve', '53');
call create_reference_mapping_msf_internal('Open biopsy of soft tissue', '54');
call create_reference_mapping_msf_internal('Osteotomy', '55');
call create_reference_mapping_msf_internal('Other skeletal traction', '56');
call create_reference_mapping_msf_internal('Paranasal sinusectomy', '57');
call create_reference_mapping_msf_internal('Partial thickness skin graft', '58');
call create_reference_mapping_msf_internal('Peripheral nerve or ganglion decompression or lysis of adhesions', '59');
call create_reference_mapping_msf_internal('Peripheral vascular shunt or bypass', '60');
call create_reference_mapping_msf_internal('Plaster of Paris (POP)', '61');
call create_reference_mapping_msf_internal('Plastic repair by z plasty', '62');
call create_reference_mapping_msf_internal('Prosthetic dental implant / Endosseous dental implant', '63');
call create_reference_mapping_msf_internal('Reconstruction procedure', '64');
call create_reference_mapping_msf_internal('Reconstruction with free flap', '65');
call create_reference_mapping_msf_internal('Reconstruction with local flap', '66');
call create_reference_mapping_msf_internal('Release [excision] scar contracture', '67');
call create_reference_mapping_msf_internal('Removal of an external fixation device', '68');
call create_reference_mapping_msf_internal('Removal of external fixator pin', '69');
call create_reference_mapping_msf_internal('Removal of foreign body or device from skin and subcutaneous cell tissue', '70');
call create_reference_mapping_msf_internal('Removal of K-wire', '71');
call create_reference_mapping_msf_internal('Removal of nail', '72');
call create_reference_mapping_msf_internal('Removal of plate from bone', '73');
call create_reference_mapping_msf_internal('Removal of screws from bone', '74');
call create_reference_mapping_msf_internal('Removal of sutures (clips etc.), skin', '75');
call create_reference_mapping_msf_internal('Removal of tissue expander from skin or soft tissue', '76');
call create_reference_mapping_msf_internal('Repair of tendon', '77');
call create_reference_mapping_msf_internal('Revision of scar', '78');
call create_reference_mapping_msf_internal('Sequestrectomy', '79');
call create_reference_mapping_msf_internal('Sinusectomy, maxillary', '80');
call create_reference_mapping_msf_internal('Skin flap operation', '81');
call create_reference_mapping_msf_internal('Skin graft operation', '82');
call create_reference_mapping_msf_internal('Specimen collection for microbiology, swab', '83');
call create_reference_mapping_msf_internal('Surgical extraction of tooth', '84');
call create_reference_mapping_msf_internal('Tendon graft', '85');
call create_reference_mapping_msf_internal('Tendon release', '86');
call create_reference_mapping_msf_internal('Tendon transfer or transplantation', '87');
call create_reference_mapping_msf_internal('Tenorrhaphy / suture of tendon', '88');
call create_reference_mapping_msf_internal('Thinning of skin flap', '89');
call create_reference_mapping_msf_internal('Wound drainage', '90');
call create_reference_mapping_msf_internal('X-plasty', '91');
call create_reference_mapping_msf_internal('Debridement of bone', '92');
call create_reference_mapping_msf_internal('Infected sinusectomy', '93');
call create_reference_mapping_msf_internal('Quadricepsplasty', '94');
call create_reference_mapping_msf_internal('Dental extraction', '95');
call create_reference_mapping_msf_internal('Pollicisation of finger or thumb', '96');
call create_reference_mapping_msf_internal('Dynamization of external fixator', '97');
call create_reference_mapping_msf_internal('Elongation of tendon achilles (ETA)', '98');
call create_reference_mapping_msf_internal('Posteromedial release of clubfoot', '99');
call create_reference_mapping_msf_internal('Excision of head of ulna', '100');
call create_reference_mapping_msf_internal('Ligament reconstruction', '101');
call create_reference_mapping_msf_internal('Epiphysiodesis', '102');
call create_reference_mapping_msf_internal('Corrective osteotomy', '103');
call create_reference_mapping_msf_internal('Site, Jaw', '30');
call create_reference_mapping_msf_internal('Site, Abdomen', '31');
call create_reference_mapping_msf_internal('Humerus proximal', '32');
call create_reference_mapping_msf_internal('Humerus shaft', '33');
call create_reference_mapping_msf_internal('Humerus distal', '34');
call create_reference_mapping_msf_internal('Radius proximal', '35');
call create_reference_mapping_msf_internal('Radius shaft', '36');
call create_reference_mapping_msf_internal('Radius distal', '37');
call create_reference_mapping_msf_internal('Ulna proximal', '38');
call create_reference_mapping_msf_internal('Ulna shaft', '39');
call create_reference_mapping_msf_internal('Ulna distal', '40');
call create_reference_mapping_msf_internal('Carpal', '41');
call create_reference_mapping_msf_internal('Metacarpals', '42');
call create_reference_mapping_msf_internal('Phalanges', '43');
call create_reference_mapping_msf_internal('Hip joint', '44');
call create_reference_mapping_msf_internal('Femur proximal', '45');
call create_reference_mapping_msf_internal('Femur shaft', '46');
call create_reference_mapping_msf_internal('Femur distal', '47');
call create_reference_mapping_msf_internal('Tibia proximal', '48');
call create_reference_mapping_msf_internal('Tibia shaft', '49');
call create_reference_mapping_msf_internal('Tibia distal', '50');
call create_reference_mapping_msf_internal('Fibula proximal', '51');
call create_reference_mapping_msf_internal('Fibula shaft', '52');
call create_reference_mapping_msf_internal('Fibula distal', '53');
call create_reference_mapping_msf_internal('Site, Median', '54');
call create_reference_mapping_msf_internal('Site, Ulnar', '55');
call create_reference_mapping_msf_internal('Site, Brachial plexus', '56');
call create_reference_mapping_msf_internal('Site, Radial', '57');
call create_reference_mapping_msf_internal('Site, Axillary', '58');
call create_reference_mapping_msf_internal('Site, Sciatic', '59');
call create_reference_mapping_msf_internal('Site, Tibial', '60');
call create_reference_mapping_msf_internal('Site, Craniofacial', '61');
call create_reference_mapping_msf_internal('Site, Mid-face excl. orbit', '62');
call create_reference_mapping_msf_internal('Site, Orbit', '63');
call create_reference_mapping_msf_internal('Site, Mandible', '64');
call create_reference_mapping_msf_internal('Internal', '1');
call create_reference_mapping_msf_internal('External', '2');
call create_reference_mapping_msf_internal('Plate', '1');
call create_reference_mapping_msf_internal('Wires', '2');
call create_reference_mapping_msf_internal('Screws', '3');
call create_reference_mapping_msf_internal('Intramedullary nails', '4');
call create_reference_mapping_msf_internal('More than 6 months', '1');
call create_reference_mapping_msf_internal('Less than 6 months', '2');
call create_reference_mapping_msf_internal('Negative', '0');
call create_reference_mapping_msf_internal('Weight Loss', '1');
call create_reference_mapping_msf_internal('Fatigue', '2');
call create_reference_mapping_msf_internal('Fever', '3');
call create_reference_mapping_msf_internal('Night Sweats', '4');
call create_reference_mapping_msf_internal('Pain', '5');
call create_reference_mapping_msf_internal('Cough', '1');
call create_reference_mapping_msf_internal('Shortness Of Breath', '2');
call create_reference_mapping_msf_internal('Chest Pain', '3');
call create_reference_mapping_msf_internal('Edema', '5');
call create_reference_mapping_msf_internal('Nausea', '1');
call create_reference_mapping_msf_internal('Pain after meals', '2');
call create_reference_mapping_msf_internal('Heartburn', '3');
call create_reference_mapping_msf_internal('Diarrhea', '4');
call create_reference_mapping_msf_internal('Constipation', '5');
call create_reference_mapping_msf_internal('Vomiting', '6');
call create_reference_mapping_msf_internal('Black/Tarry Stool', '7');
call create_reference_mapping_msf_internal('Bloody Stool', '8');
call create_reference_mapping_msf_internal('Incontinence', '1');
call create_reference_mapping_msf_internal('Hesitancy', '2');
call create_reference_mapping_msf_internal('Hematuria', '3');
call create_reference_mapping_msf_internal('Dysuria', '4');
call create_reference_mapping_msf_internal('Abnormal menses', '5');
call create_reference_mapping_msf_internal('Kidney Stones', '6');
call create_reference_mapping_msf_internal('Paresthesia', '1');
call create_reference_mapping_msf_internal('Focal Weakness', '2');
call create_reference_mapping_msf_internal('Confusion', '3');
call create_reference_mapping_msf_internal('Headache', '4');
call create_reference_mapping_msf_internal('Dizziness', '5');
call create_reference_mapping_msf_internal('Vision Difficulties', '1');
call create_reference_mapping_msf_internal('Decreased Hearing', '2');
call create_reference_mapping_msf_internal('Epistaxis', '3');
call create_reference_mapping_msf_internal('Gum Bleeding', '4');
call create_reference_mapping_msf_internal('Dental Caries', '5');
call create_reference_mapping_msf_internal('Difficulty Chewing', '6');
call create_reference_mapping_msf_internal('Dysphagia', '7');
call create_reference_mapping_msf_internal('Joint Pain', '1');
call create_reference_mapping_msf_internal('Joint Stiffness', '2');
call create_reference_mapping_msf_internal('Muscular Soreness', '3');
call create_reference_mapping_msf_internal('Generalized Weakness', '4');
call create_reference_mapping_msf_internal('Joint Swelling', '5');
call create_reference_mapping_msf_internal('PE, General examination', 'PE_GEN');
call create_reference_mapping_msf_internal('PE, HEENT examination', 'PE_HEENT');
call create_reference_mapping_msf_internal('PE, Chest examination', 'PE_CHEST');
call create_reference_mapping_msf_internal('PE, Heart examination', 'PE_HEART');
call create_reference_mapping_msf_internal('PE, Abdomen examination', 'PE_ABDOMEN');
call create_reference_mapping_msf_internal('PE, Rectal and genitalia examination', 'PE_RECTAL_GENITAL');
call create_reference_mapping_msf_internal('PE, Extremities examination', 'PE_EXTREMITIES');
call create_reference_mapping_msf_internal('PE, Neurologic examination', 'PE_NEURO');
call create_reference_mapping_msf_internal('AIA, Date of consultation', 'D_CONSULTATION');
call create_reference_mapping_msf_internal('AIA, Past medical history', 'MEDHX');
call create_reference_mapping_msf_internal('AIA, Past medical history, other', 'OTHER_MEDHX');
call create_reference_mapping_msf_internal('AIA, Is the patient allergic to any drugs / medications ?', 'HXALLERGY');
call create_reference_mapping_msf_internal('AIA, Type of medication allergy', 'TYPE_ALLERGY');
call create_reference_mapping_msf_internal('AIA, Previous Anaesthesia history', 'HXANAESTH');
call create_reference_mapping_msf_internal('AIA, Specify number of times receiving anaesthesia', 'TIMES_RECANAESTH');
call create_reference_mapping_msf_internal('AIA, Adverse reaction to anaesthesia', 'AE_ANAESTH');
call create_reference_mapping_msf_internal('AIA, Comments about adverse reaction', 'COMMENTS_AE_ANAESTH');
call create_reference_mapping_msf_internal('AIA, Personal history of blood transfusion', 'HXTRANSFUSION');
call create_reference_mapping_msf_internal('AIA, Did an incident occur during previous blood transfusion', 'HXINCIDENT_TRANSF');
call create_reference_mapping_msf_internal('AIA, Describe', 'DESCRIBE');
call create_reference_mapping_msf_internal('AIA, Mallampati class', 'MALLAMPATI');
call create_reference_mapping_msf_internal('AIA, Mouth opening', 'MOUTHOPENING');
call create_reference_mapping_msf_internal('AIA, ASA score', 'ASA');
call create_reference_mapping_msf_internal('AIA, Planned anaesthesia technique', 'PLANNED_ANAESTH');
call create_reference_mapping_msf_internal('AIA, Does the patient need fiberoptic ?', 'FIBEROPTIC');
call create_reference_mapping_msf_internal('AIA, Remarks-anaesthetist', 'REMARKS_ANAESTH');
call create_reference_mapping_msf_internal('AIA, Outcome of anaesthesia initial assessment', 'OUTCOME_ANAESTH_IA');
call create_reference_mapping_msf_internal('AIA, Outcome of anaesthesia initial assessment, comments', 'COMMENTS_ANAESTH_IA');
call create_reference_mapping_msf_internal('AIA, I discussed the risks and benefits of anaesthesia and answered all questions', 'RISKS_DISCUS');
call create_reference_mapping_msf_internal('None', '0');
call create_reference_mapping_msf_internal('Congenital lung disease', '3');
call create_reference_mapping_msf_internal('Cough or cold (present time)', '5');
call create_reference_mapping_msf_internal('Sleep apnea', '7');
call create_reference_mapping_msf_internal('Asthma', '4');
call create_reference_mapping_msf_internal('Emphysema', '8');
call create_reference_mapping_msf_internal('Congential heart disease', '13');
call create_reference_mapping_msf_internal('History of hypertension', '1');
call create_reference_mapping_msf_internal('History of Rheumatic fever', '14');
call create_reference_mapping_msf_internal('History of valve disease', '15');
call create_reference_mapping_msf_internal('History of MI', '16');
call create_reference_mapping_msf_internal('History of palpitations', '2');
call create_reference_mapping_msf_internal('History of heart problems (within last six months)', '17');
call create_reference_mapping_msf_internal('Congenital renal disease', '18');
call create_reference_mapping_msf_internal('History of renal infection', '19');
call create_reference_mapping_msf_internal('History of renal stones', '20');
call create_reference_mapping_msf_internal('History of renal failure', '21');
call create_reference_mapping_msf_internal('Diabetes', '6');
call create_reference_mapping_msf_internal('Thyroid hormone diseases', '22');
call create_reference_mapping_msf_internal('History of corticosteroid drugs', '23');
call create_reference_mapping_msf_internal('Congenital disorders of the nervous system', '24');
call create_reference_mapping_msf_internal('Epilepsy  or seizure', '11');
call create_reference_mapping_msf_internal('History of CVA - TIA', '25');
call create_reference_mapping_msf_internal('Spinal cord disease', '26');
call create_reference_mapping_msf_internal('History of upper GI bleeding', '27');
call create_reference_mapping_msf_internal('History of jaundice', '10');
call create_reference_mapping_msf_internal('History of cirrhosis', '28');
call create_reference_mapping_msf_internal('History of hepatitis', '12');
call create_reference_mapping_msf_internal('History of blood disorder', '29');
call create_reference_mapping_msf_internal('History of anemia', '30');
call create_reference_mapping_msf_internal('History of frequent bleeding', '31');
call create_reference_mapping_msf_internal('Abnormal blood clotting', '32');
call create_reference_mapping_msf_internal('History of cancer', '33');
call create_reference_mapping_msf_internal('Local', '1');
call create_reference_mapping_msf_internal('General', '2');
call create_reference_mapping_msf_internal('Regional', '3');
call create_reference_mapping_msf_internal('Delayed recovery', '1');
call create_reference_mapping_msf_internal('Admission to ICU', '2');
call create_reference_mapping_msf_internal('Suffocation or cyanosis', '3');
call create_reference_mapping_msf_internal('Difficult intubation', '4');
call create_reference_mapping_msf_internal('Class I', '1');
call create_reference_mapping_msf_internal('Class II', '2');
call create_reference_mapping_msf_internal('Class III', '3');
call create_reference_mapping_msf_internal('Class IV', '4');
call create_reference_mapping_msf_internal('ASA I', '1');
call create_reference_mapping_msf_internal('ASA II', '2');
call create_reference_mapping_msf_internal('ASA III', '3');
call create_reference_mapping_msf_internal('ASA IV', '4');
call create_reference_mapping_msf_internal('ASA V', '5');
call create_reference_mapping_msf_internal('ASA VI', '6');
call create_reference_mapping_msf_internal('GAI', '1');
call create_reference_mapping_msf_internal('GAO', '2');
call create_reference_mapping_msf_internal('GAL', '3');
call create_reference_mapping_msf_internal('RSA', '4');
call create_reference_mapping_msf_internal('RPX', '5');
call create_reference_mapping_msf_internal('RTA', '6');
call create_reference_mapping_msf_internal('RAO', '7');
call create_reference_mapping_msf_internal('LOA', '8');
call create_reference_mapping_msf_internal('SED', '9');
call create_reference_mapping_msf_internal('INF', '10');
call create_reference_mapping_msf_internal('Ready for surgery', '1');
call create_reference_mapping_msf_internal('One week of preparation and consultation', '2');
call create_reference_mapping_msf_internal('Few weeks of preparation', '3');
call create_reference_mapping_msf_internal('Return home for preparation', '4');
call create_reference_mapping_msf_internal('Unfit completely for this project', '5');