appointments: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.3/appointments-1.3.0-SNAPSHOT-2.1.0.omod
bahmni_core: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.3/bahmnicore-0.93-SNAPSHOT-2.6.0.omod
bahmni_ie_apps: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.3/bahmni.ie.apps-1.1.0-SNAPSHOT-2.5.0.omod
bahmni_msf_omod: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.3/bahmnimsf-0.93-2.1.0.omod
bahmniapps: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.3/bahmniapps-2.6.3.zip
implementer_interface: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.3/bahmni-implementer-interface-91-2.6.1.noarch.rpm
bahmni_batch: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.3/bahmni-amman-batch-1.1.0-2.4.0.noarch.rpm
print_forms: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.3/print-forms-2.0.0.zip
appointment_frontend: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.3/appointment-frontend-2.6.2.zip
visit_close_omod: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.3/visit-close-module-0.93-2.3.1.omod
emr_api_omod: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.3/emrapi-omod-1.24.7-2.1.0-SNAPSHOT.omod
event_omod: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.3/event-2.8.0-2.1.0.omod
uiframework: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.3/uiframework-3.19-2.1.0.omod
operationtheater_omod: https://stable.s3.ap-south-1.amazonaws.com/msf-release-2.6.3/operationtheater-1.3.0.omod
